#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  local url_kubernetes_Darwin="https://dl.k8s.io/v${KUBERNETES_VERSION}/kubernetes-client-darwin-amd64.tar.gz"
  local url_kubernetes_Linux="https://dl.k8s.io/v${KUBERNETES_VERSION}/kubernetes-client-linux-arm64.tar.gz"

  local url_kubernetes="url_kubernetes_$(uname -s)"
  local fnm_kubernetes="$(basename "${!url_kubernetes}")"
  cache curl "$fnm_kubernetes" "${!url_kubernetes}"

  mkdir -p "$shome/vendor"
  pushd "$shome/vendor"
  tar xvfz "${BASEBOX_CACHE}/curl/$fnm_kubernetes"
  popd
}

main "$@"
