#!/usr/bin/env bash

function _kubernetes_profile {
  local shome="${_kubernetes_home:-"$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"}"
  PATH="$shome/vendor/kubernetes/client/bin:$PATH"
}

_kubernetes_profile
