#!/usr/bin/env bash

function version {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  local ver_kubernetes="$(kubectl version --client | perl -pe 's{.*?GitVersion:"v([^"-]+).*$}{$1}')"
  jq -n --arg kubernetes "$ver_kubernetes" '{kubernetes: $kubernetes}'
}

version "$@"
